js/actions/nglRenderActions.js, js/components/SummaryCmpd.js, js/components/compoundList.js, js/components/compoundView.js, js/components/eventSlider.js, js/components/generalComponents.js, js/components/header.js, js/components/menuView.js, js/components/molGroupList.js, js/components/moleculeView.js, js/components/nglComponents.js, js/components/panddaSiteList.js, js/components/panddaSlider.js, js/components/summaryView.js, js/components/targetList.js, js/containers/app.js, js/reducers/selectionReducers.js, js/utils/ngl_functions.js, js/utils/ngl_views.js, js/utils/util.js, package.json
- Update to latest webpack
- Added code linting and linted code
=> Update to deps and linting

Jenkinsfile
Adds a Jenkinsfile stub. At the moment nothing much goes on here, it just provides a hook into Jenkins.
=> OpenShift CD/CD integration

js/components/moleculeView.js, js/components/targetList.js, package.json
- Update webpack to v4.12.0
- Update the complex getter
- Update the target loader
=> Include full URLs in all NGL components

js/components/compoundView.js
- Required nasty hard coding
- I obviously still don't understand Object.assign
=> Fix compound view issues

js/components/hotspotList.js, js/components/hotspotView.js
- repair bug introduced in hotspot PR
=> Fix width bug

Jenkinsfile
Adds calls to clack for build/alert notification
=> Adds Slack notifications to the Jenkinsfile

js/components/compoundList.js, js/components/compoundView.js, js/components/summaryView.js, js/containers/fraggleBoxHolder.js, js/containers/previewHolder.js, js/reducers/apiReducers.js, js/reducers/selectionReducers.js
- Moved react-keydown capture to preview-holder - full key capture. 
- Frees up componentWillReceiveProps for updating compound list. 
- Fix to remove_from_to_buy_list -slice for deep copy, to ensure proper update. 
- Fix to remove_from_to_buy_list - no longer removes final compound. 
- Addition of clear all button for to_buy_list.
=> Bug fix: Cursor capture and update errors in compound list

js/components/compoundList.js, js/components/compoundView.js, js/components/generalComponents.js, js/components/header.js, js/components/modalLoadingScreen.js, js/components/moleculeView.js, js/components/summaryView.js, js/components/targetList.js, js/configureStore.js, js/containers/app.js, js/containers/fraggleBoxHolder.js, js/containers/previewHolder.js, js/utils/ngl_functions.js, js/utils/util.js
- Fixed bug which caused navigation to end of compound list on rightClick after onClick action.
- Compound list shows as loading during loading. 
- Cleaned up unused code.
=> Bug Fix - navigation and compound loading.

js/components/compoundList.js, js/components/compoundView.js, js/components/summaryView.js, js/reducers/selectionReducers.js
- Update vector view to fragments
- Show zero cost if no compounds chosen
=> Updates to compound selectors

js/components/generalComponents.js, js/components/targetList.js
https://github.com/xchem/fragalysis-frontend/issues/83
https://sentry.io/share/issue/6c03d91fa9294e14a04ac417701f6cae/
=> Fixes error when no molecule groups exist

js/components/compoundList.js, js/components/generalComponents.js, js/components/header.js, js/components/moleculeView.js, js/components/nglComponents.js, js/components/targetList.js, js/components/updateOrientation.js, js/containers/fraggleBoxHolder.js, js/containers/previewHolder.js
- restore cursor key compound navigation
- clean up
- set current vector in FraggleBox
- FraggleBox capture background colour
=> Restore cursor navigation functionality

js/components/session/withSessionManagement.js, js/reducers/ngl/dispatchActions.js
Set proper target name in header + fixed possible case of not working "Save Session As" and "Share Snapshot".
=> Update with fixed target name and buttons

docker-compose.localhost.yml, js/components/common/Modal/index.js, js/components/common/Surfaces/Panel/index.js, js/components/preview/compounds/redux/dispatchActions.js, js/components/preview/molecule/moleculeList.js, js/components/preview/molecule/moleculeListSortFilterDialog.js, js/components/preview/molecule/moleculeView.js, js/components/preview/molecule/redux/constants.js, js/components/preview/molecule/redux/dispatchActions.js, js/components/preview/summary/redux/dispatchAction.js, js/components/preview/summary/redux/reducer.js, js/components/userFeedback/browserApi.js, js/components/userFeedback/githubApi.js, js/components/userFeedback/redux/reducer.js, js/components/userFeedback/reportForm.js, js/reducers/selection/actions.js, js/reducers/selection/constants.js, js/reducers/selection/dispatchActions.js, js/reducers/selection/selectionReducers.js, js/reducers/selection/selectors.js, js/theme/palette.js, package.json, yarn.lock
Moved hit filter from filter dialog into "Hit navigator" header and changed its behaviour from excluding molecules to colour matched values in molecules instead.
Fixed download of CSV file when some compounds were picked.
- resolves m2ms/fragalysis-frontend#67
- resolves m2ms/fragalysis-frontend#97
- resolves m2ms/fragalysis-frontend#98
- resolves m2ms/fragalysis-frontend#170
- resolves m2ms/fragalysis-frontend#186
19.3. update - added scribble
- resolves m2ms/fragalysis-frontend#120
=> added predefined filter in "Hit navigator" header and fixed "Download CSV"

js/components/header/index.js, js/components/preview/molecule/moleculeView.js, js/theme/palette.js, package.json
Added progress bar under header instead of the loading circle, cursor changed into arrow with hourglass, "anti-interaction" layer made transparent.
Non matching values of predefined filter are coloured to pale red.
- resolves m2ms/fragalysis-frontend#122
- resolves m2ms/fragalysis-frontend#207
=> changed loading behaviour

js/components/nglView/renderingObjects.js, js/components/preview/molecule/moleculeList.js, js/components/preview/molecule/moleculeListSortFilterDialog.js, js/components/preview/molecule/moleculeListSortFilterItem.js, js/components/preview/molecule/moleculeView.js, js/components/preview/molecule/redux/constants.js, js/components/preview/molecule/redux/dispatchActions.js, js/reducers/ngl/actions.js, js/reducers/ngl/nglReducers.js, package.json
Added sort options for site ID and hit ID.
Temporarily removed status labels.
- resolves m2ms/fragalysis-frontend#183
- resolves m2ms/fragalysis-frontend#208
=> added sort by site and hit, removed status labels

js/components/common/Modal/index.js, js/components/userFeedback/reportForm.js, js/utils/useResizeObserver.js, package.json, yarn.lock
Added resizable possibility for issue/idea report dialog.
- resolves m2ms/fragalysis-frontend#211
=> resizable reporting

js/components/preview/moleculeGroups/molGroupChecklist.js
Adjusted length of site label for list size and added site description into its tooltip too; iteration to m2ms/fragalysis-frontend#225.
=> trimmed long descriptions of sites and put them into tooltip

js/components/nglView/generatingObjects.js, js/components/nglView/nglView.js, js/components/nglView/renderingObjects.js, js/components/preview/molecule/moleculeList.js, js/components/preview/molecule/moleculeView.js, js/components/preview/molecule/molecules_helpers.js, js/components/preview/molecule/redux/dispatchActions.js, js/components/preview/moleculeGroups/redux/dispatchActions.js, js/reducers/ngl/dispatchActions.js, js/reducers/selection/selectionReducers.js
Added (S)urface toggle, minor fixes.
- resolves m2ms/fragalysis-frontend#227
- resolves m2ms/fragalysis-frontend#228
- resolves m2ms/fragalysis-frontend#235
- resolves m2ms/fragalysis-frontend#236
=> added surface toggle

js/reducers/ngl/nglReducers.js
Fixed broken focus on first ligand of site on target change.
- resolves m2ms/fragalysis-frontend#246
=> fixed ligand focus on target change

js/components/preview/Preview.js, js/components/preview/molecule/moleculeList.js, js/components/preview/molecule/redux/dispatchActions.js, package.json
https://github.com/m2ms/fragalysis-frontend/issues/442
=> #442 - Sort/filter modal is broke

js/components/preview/tags/redux/dispatchActions.js, js/components/snapshot/downloadPdb.js, js/components/snapshot/modals/downloadStructuresDialog.js, package.json
- bumped version to 0.10.65
commit 909e2b2192c3988d3b40c088f09d95fdd55e48a5
Author: Boris Kovar <boris.kovar@m2ms.sk>
Date:   Thu Feb 3 08:29:21 2022 +0100
- fixed #783 and hopefully also #758
=> Squashed commit of the following:

js/components/header/index.js, js/components/preview/ResizableLayout.js, package.json
=> misc fixes
